// * next.js imports *
import Head from 'next/head';

// * third party library imports *
// import PropTypes from 'prop-types';
// import sanityClient from '@/sanity/client';

// * custom component imports *
import AppFooter from '@/components/app-footer/AppFooter';
import AppHeader from '@/components/app-header/AppHeader';
import BlogIndexHero from '@/components/heroes/blog-index-hero/BlogIndexHero';
import BlogList from '@/components/blog/blog-list/BlogList';

export default function Blog() {
  return (
    <>
      <Head>
        <title>Pruitt Strategic Security – Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppHeader />
      <main>
        <BlogIndexHero />
        <BlogList />
      </main>
      <AppFooter />
    </>
  );
}
