// * next.js imports *
import Head from 'next/head';

// * third party library imports *
// import PropTypes from 'prop-types';
// import sanityClient from '@/sanity/client';

// * custom component imports *
import AppFooter from '@/components/app-footer/AppFooter';
import AppHeader from '@/components/app-header/AppHeader';

export default function Home() {
  return (
    <>
      <Head>
        <title>Pruitt Strategic Security</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppHeader />
      <main>
        <h1>Welcome to Pruitt Strategic Security</h1>
        <p>Your trusted security partner.</p>
      </main>
      <AppFooter />
    </>
  );
}
