// * next.js imports *
import Head from 'next/head';

// * third party library imports *
// import PropTypes from 'prop-types';
// import sanityClient from '@/sanity/client';

// * custom component imports *
import About from '@/components/about/About';
import AppFooter from '@/components/app-footer/AppFooter';
import AppHeader from '@/components/app-header/AppHeader';
import Blog from '@/components/blog/Blog';
import Contact from '@/components/contact/Contact';
import HomeHero from '@/components/heroes/home-hero/HomeHero';
import Testimonials from '@/components/testimonials/Testimonials';

export default function Home() {
  return (
    <>
      <Head>
        <title>Pruitt Strategic Security</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppHeader />
      <main>
        <HomeHero />
        <About />
        <Testimonials />
        <Blog />
        <Contact />
      </main>
      <AppFooter />
    </>
  );
}
